Hashtaglist:
    type: entity
    table: hashtaglist
    id:
        hashtaglistId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: hashtaglist_id
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: string
            nullable: false
            length: 128
            fixed: false
            column: user_id
        hashtag:
            type: string
            nullable: false
            length: 256
            fixed: false
    lifecycleCallbacks: {  }
