models\entities\Tweet:
    type: entity
    table: tweet
    id:
        tweetId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: tweet_id
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: string
            nullable: false
            length: 152
            fixed: false
            column: user_id
        text:
            type: string
            nullable: false
            length: 256
            fixed: false
        date:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
