models\entities\User:
    type: entity
    table: user
    id:
        userId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: user_id
            generator:
                strategy: IDENTITY
    fields:
        oauthToken:
            type: string
            nullable: false
            length: 256
            fixed: false
            column: oauth_token
        oauthTokenSecret:
            type: string
            nullable: false
            length: 256
            fixed: false
            column: oauth_token_secret
    lifecycleCallbacks: {  }
